### ISSUE TITLE
JWT auth error

### ISSUE THREAD

**Issue by iamoskvin** [voximplant/apiclient-php#1]
В файле Token.php:

if (file_exists($keyPath)) {
  $privateKey = json_decode(file_get_contents($keyPath));
  if(!empty($privateKey->result->private_key)) {
...

Откуда берется поле result? Если его убрать, то все работает корректно. То есть по идее должно быть $privateKey->private_key и далее по файлу так же.

**Comment by MikhailUtkin** [comment]
Дополнен метод generateAuthorizationHeader. 

Можно использовать json с result и без него:
{"result": {"account_email":"test@test.com"}}
или
{"account_email":"test@test.com"}

**Comment by tezrik** [comment]
Еще вот здесь https://github.com/voximplant/apiclient-php/blob/eab750218b21bd26a3817fbf583533cb4038c7ed/src/VoximplantApi.php#L188  

При получении API Tokena из панели управления файл выдается без result

**Comment by MikhailUtkin** [comment]
Здравствуйте! Выкатили обновление с исправлением!
