### ISSUE TITLE
Authorization failed 

### ISSUE THREAD

**Issue by tezrik** [voximplant/apiclient-php#3]
$patch = base_path('voximplant.json');
$voxApi = new VoximplantApi($patch);
$params = new SendSmsMessageParams();
$params->source = '447460546532';
$params->destination = '79519316710';
$params->sms_body = $phone_code;
/** @var SendSmsMessageReturn $result */
$result = $voxApi->SMS->SendSmsMessage($params);

{"error":{"msg":"Authorization failed.","code":100},"errors":[{"msg":"Authorization failed.","code":100}]}

"result": {
		"account_email": "****",
		"account_id": 3113892,
		"key_id": "****",
		"private_key": "*****"
	}

**Comment by MikhailUtkin** [comment]
Здравствуйте!

Добавьте [роль](https://manage.voximplant.com/settings/service_accounts) токену. 

![Снимок экрана 2019-07-04 в 11 07 49](https://user-images.githubusercontent.com/48284933/60650035-fd3ed500-9e4b-11e9-8dec-9b5dd7e9ca48.png)

**Comment by tezrik** [comment]
какая роль необходима для отправки смс ?

**Comment by MikhailUtkin** [comment]
Роли для метода SendSmsMessage:  Owner, Admin, Developer.

**Comment by umbrella-vitaliy-popov** [comment]
Thanks you

**Comment by EmmaVvv** [comment]
Получаю в запросе вебхука url записи разговора, далее создал сервис аккаунт и дал ему все существующие роли, сгенерировал Authorization хидер при помощи сдк, отправляю запрос на загрузку записи, получаю 401 ошибку
